### ISSUE TITLE
Add support for overriding hostname and ip fields

### ISSUE THREAD

**Issue by SEJeff** [jaegertracing/jaeger-client-cpp#105]
This mirrors the python and java clients: jaegertracing/jaeger-client-python#167 and jaegertracing/jaeger-client-java#371

C++ isn't a language I'm fluent in, but it looks like [this is the relevant code to be changed](https://github.com/jaegertracing/jaeger-client-cpp/blob/75191fc82acd616ed3c5ed525afefcbf8eed45a1/src/jaegertracing/Tracer.h#L244-L248). I might take a stab at fixing this myself.

The goal is to have the tracing on the the kubernetes ingress controller report the actual host it is running on via a magical env var passed to the pod via the downward api.

**Comment by isaachier** [comment]
OK cool. Consider using `getenv` so this can use an environment variable as described here: https://www.jaegertracing.io/docs/client-features/. Not sure if one exists for hostname and/or IP but it would make sense to me. @yurishkuro does that make sense to use an environment variable?

**Comment by yurishkuro** [comment]
sounds like there are two enhancements:
  1. setting tracer tags via `JAEGER_TAGS` env variable as supported in other clients
  1. bypassing hostname/ip logic in the tracer when `hostname`/`ip` tags are given

Don't know about kubernetes, pretty sure it allows setting any kind of env variables, but not sure if it supports substitutions so that one could define `JAEGER_TAGS=hostname=$NODE_HOSTNAME`

**Comment by SEJeff** [comment]
@yurishkuro yes that seems sensible. I'm looking for #2 as kubernetes can not do substitutions for env variables provided in the way I need them (via the downwards api).

**Comment by rredkovich** [comment]
There is relevant issue for nginx jaeger plugin which depends on this feature to be able to be configured with env vars: https://github.com/opentracing-contrib/nginx-opentracing/issues/68

In short: a jaeger agent is placed on every node in kubernetes deployment and to eliminate extra time consumption packets should be send straight to node IP. Node IP where pod is currently deployed could be set dynamically into env var:
```
        env:
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```
