### ISSUE TITLE
tracer.Inject(SpanContext&, HTTPHeadersWriter&) does not use HTTPHeaderPropagator

### ISSUE THREAD

**Issue by HugoMFernandes** [jaegertracing/jaeger-client-cpp#107]
`tracer.Inject(SpanContext&, HTTPHeadersWriter&)` is currently using `TextMapPropagator` instead of `HTTPHeaderPropagator`.

Here's the bug: https://github.com/jaegertracing/jaeger-client-cpp/blob/75191fc82acd616ed3c5ed525afefcbf8eed45a1/src/jaegertracing/Tracer.h#L151

I'm guessing this was a copy/paste problem (`Tracer::Extract` is fine). I'll create a PR with the fix in a second.

**Comment by isaachier** [comment]
Fixed in #108.
