### ISSUE TITLE
Propagate opentracing-cpp v1.4.1

### ISSUE THREAD

**Issue by dansandu** [jaegertracing/jaeger-client-cpp#110]
Version 1.4.1 of `opentracing-cpp` fixes some Windows build issues. Can we propagate them here? Also, has anyone tried to build this project on Windows?

**Comment by yurishkuro** [comment]
I don't think anyone tried for Windows, you are welcome to try and put a PR.

**Comment by mdouaihy** [comment]
I identified an incompatibility between the release1.4.1 of OpenTracing and Hunter. I already provided a fix for that and a PR was issued.

Once accepted and merged, I already have a change ready to push the new release into Hunter. Only then we can have the new release available here.

**Comment by mdouaihy** [comment]
You can try locally on your machine by changing the hunter version in the main CMake file. You can use the one I packaged
```
HunterGate(
    URL "https://github.com/mdouaihy/hunter/archive/v0.21.10.tar.gz"
    SHA1 "4fcb0fd68f0eca9753312dc26442ab76f8efcbc1"
)
```

**Comment by dansandu** [comment]
@mdouaihy works like a charm, thanks! At first it was complaining that some file paths were exceeding 260 characters (I'm building on Windows 7) but I moved the hunter repository upper in the folder hierarchy and set `CMAKE_OBJECT_PATH_MAX` to 240 in `CMakeLists.txt`.
