### ISSUE TITLE
Replace MIT with Apache license

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-cpp#116]
https://github.com/jaegertracing/jaeger-client-cpp/blob/master/.ycm_extra_conf.py

**Comment by isaachier** [comment]
Surprised this is still here.

**Comment by yurishkuro** [comment]
if it's not needed, please delete the file, otherwise update the license to apache

**Comment by isaachier** [comment]
Sorry I meant the license "is still here" not the file.
