### ISSUE TITLE
DynamicallyLoadTracerTest will not be built with cmake command from 'build-plugin.sh' 

### ISSUE THREAD

**Issue by ppggff** [jaegertracing/jaeger-client-cpp#119]
I tried cmake command in 'build-plugin.sh', but DynamicallyLoadTracerTest will not be built.
It seems target `jaegertracing` should change to `jaegertracing_plugin` in CMakeLists.txt.

```
...
if(TARGET jaegertracing)
    add_executable(DynamicallyLoadTracerTest
    src/jaegertracing/DynamicallyLoadTracerTest.cpp)
...
```

**Comment by isaachier** [comment]
Ya there's a reason for that. The plugin is supposed to compile the opentracing-cpp library into the `libjaegertracing_plugin.so` file. For reasons I know longer remember, this creates a complicated situation for builder the dynamic library test. To test this, I'd suggest looking at some of the applications @rnburn has developed that rely on plugins, or use the opentracing-cpp dynamic loading test executable to load the Jaeger library.
