### ISSUE TITLE
Remove Thrift headers from Jaeger public headers

### ISSUE THREAD

**Issue by sebastian-garofalo** [jaegertracing/jaeger-client-cpp#121]
Hi

The example app works, although one of the unit tests fails, but then when I try to use the library in my projects I get the following error.

```
In file included from /usr/local/include/jaegertracing/Tag.h:20:0,
                 from /usr/local/include/jaegertracing/LogRecord.h:20,
                 from /usr/local/include/jaegertracing/Span.h:26,
                 from /usr/local/include/jaegertracing/UDPTransport.h:20,
                 from /usr/local/include/jaegertracing/reporters/Config.h:25,
                 from /usr/local/include/jaegertracing/Config.h:23,
                 from /usr/local/include/jaegertracing/Tracer.h:28,
                 from followersServer.cc:11:
/usr/local/include/jaegertracing/thrift-gen/jaeger_types.h:12:27: fatal error: thrift/Thrift.h: No such file or directory
compilation terminated.
```
So I tried to update the thrift submodule as you mention in the README but doesn't seems to be working fine, I get:

```
sgarofalo@AR-IT08661:~/dev/jaeger-client-cpp$ find idl/thrift/ -type f -name \*.thrift -exec thrift -gen cpp -out src/jaegertracing/thrift-gen {} \;
[WARNING:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/jaeger.thrift:18] No generator named 'netcore' could be found!
[WARNING:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/zipkincore.thrift:19] No generator named 'netcore' could be found!
[WARNING:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/agent.thrift:21] No generator named 'netcore' could be found!
[WARNING:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/aggregation_validator.thrift:18] No generator named 'netcore' could be found!
[WARNING:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/baggage.thrift:18] No generator named 'netcore' could be found!
[WARNING:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/crossdock/tracetest.thrift:18] No generator named 'netcore' could be found!
[ERROR:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/crossdock/tracetest.thrift:28] (last token was 'Downstream')
Type "Downstream" has not been defined.
[WARNING:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/dependency.thrift:18] No generator named 'netcore' could be found!
[WARNING:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/jaeger.thrift:18] No generator named 'netcore' could be found!
[WARNING:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/sampling.thrift:18] No generator named 'netcore' could be found!
[WARNING:/home/sgarofalo/dev/jaeger-client-cpp/idl/thrift/zipkincore.thrift:19] No generator named 'netcore' could be found!
sgarofalo@AR-IT08661:~/dev/jaeger-client-cpp$ git apply scripts/thrift-gen.patch
error: patch failed: src/jaegertracing/thrift-gen/tracetest_types.cpp:60
error: src/jaegertracing/thrift-gen/tracetest_types.cpp: patch does not apply
error: patch failed: src/jaegertracing/thrift-gen/tracetest_types.h:61
error: src/jaegertracing/thrift-gen/tracetest_types.h: patch does not apply
```

And the original error is still present.
Does anyone knows what is going on and how can I solve it?

Thanks

**Comment by isaachier** [comment]
@sebastian-garofalo the main issue here is that `Thrift/thrift.h` is missing, and that is part of the core thrift C++ library. Please make sure you have installed the dependencies and try again. Do not use the patch and/or regenerate the files for now.

**Comment by sebastian-garofalo** [comment]
After installing thrift it got solved, weird that the example app didn't need it. Thanks

**Comment by rnburn** [comment]
@isaachier - if you use hunter to install thrift, those headers aren't going to be available in the regularly searched include paths.

is it possible to not include any of the thrift dependencies in jaeger's public headers?

**Comment by isaachier** [comment]
@rnburn if that were true, Travis would fail building. Hunter manipulates the search path to include the dependency on Thrift. As an aside, I could potentially limit Thrift headers to implementation files, but it might be a big rewrite. Not sure if it makes sense when the dependency on the Thrift library would still be necessary.

**Comment by rnburn** [comment]
@isaachier - you statically link everything into the jaeger library, so you don't need thrift after building jaeger.

Lots of people don't use cmake to build their projects. In that case, the hunter include directories wouldn't be searched unless they explicitly add flags for them.

But given that they're not needed outside the implementation files, why include them? if nothing else, it's going to make compilation slower to add unnecessary header files like that.

**Comment by isaachier** [comment]
Right I agree that might be a solvable issue. Will reopen and retitle this issue.
