### ISSUE TITLE
Document how to specify agent/collector endpoint

### ISSUE THREAD

**Issue by sebastian-garofalo** [jaegertracing/jaeger-client-cpp#122]
Hey guys

I'm trying to add jaegertracing to a C++ microservice running on an Istio mesh.

I got working the example app but I can't find a way to specify what is the collector endpoint the app will use to send the spans/traces and the only loggers I see defined do nothing or just print on screen the messages.

Can someone tell me what would be the config parameter that defines the collector to use? 
Or point me to some working example/documentation to use as a guide?

Thanks for you help

**Comment by isaachier** [comment]
Try updating the config.yml to look something like this:

```
sampler:
  samplingServerURL: <collector-url>
```

By default, the value of `collector-url` is `127.0.0.1:5778`.

**Comment by yurishkuro** [comment]
@isaachier I suggest adding a section to the readme

**Comment by sebastian-garofalo** [comment]
@isaachier 
I tried with that but it's ignoring the sampling URL and stills sends the traces to localhost:9411 
my config file looks like this:

```
disabled: false
reporter:
    logSpans: true
sampler:
  type: const
  param: 1
  samplingServerURL: zipkin.istio-system.svc.cluster.local:9411
```

Also is there any way to see logs of what the library is doing? I can't see any error logs if I stop the localhost jaeger.

**Comment by sebastian-garofalo** [comment]
I was doing that, but I can only see the traces I generate, but no errors about contacting the collector

```
void setUpTracer(const char* configFilePath)
{
    auto configYAML = YAML::LoadFile(configFilePath);
    auto config = jaegertracing::Config::parse(configYAML);
    auto tracer = jaegertracing::Tracer::make("followers-service", config, jaegertracing::logging::consoleLogger());
    opentracing::Tracer::InitGlobal(std::static_pointer_cast<opentracing::Tracer>(tracer));
}
```

And I see something like this

```
Followers Service starting...
Initializing Jaeger tracing...
INFO: Initializing logging reporter
INFO: Reporting span f218f30d30fd823b:4e0db680f75733dc:f218f30d30fd823b:1
INFO: Reporting span f218f30d30fd823b:f218f30d30fd823b:0:1
```

**Comment by isaachier** [comment]
The collector manages the sampling strategy. The agent forwards traces to the collector from your application. It seems you meant to change the agent endpoint. That requires updating the reporting config, not the sampling config. Please override the localAgentHostPort property of the reporter section like so:

```
reporter:
    logSpans: true
    localAgentHostPort: <agent-host-port>
```

**Comment by isaachier** [comment]
Final thought: you might have the correct setup in your application, but your agent might experience errors when it sends traces to an invalid endpoint. See the main Jaeger repo for how to set up the agent etc.

**Comment by sebastian-garofalo** [comment]
Will do, thanks a lot for your help @isaachier

**Comment by isaachier** [comment]
No problem, I'll try to add some stuff to the README about this.

**Comment by tarunz** [comment]
```
reporter:
    logSpans: true
    localAgentHost: 10.244.1.140
    localAgentHostPort: 6832
```
Setting yml like this, throws an error: 
```
Running main function
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot connect socket to remote address { family=2, addr=0.0.26.176, port=0 }
Aborted (core dumped)
```
Kindly help @isaachier , how can I define agentHost, agentPort?

**Comment by MikeGoldsmith** [comment]
@tarunz you pass the host and port in the same parameter:
`localAgentHostPort: 10.244.1.140:6832`
