### ISSUE TITLE
The C++ Jaeger client always populates the "ip" tag with 127.0.0.1

### ISSUE THREAD

**Issue by tudor** [jaegertracing/jaeger-client-cpp#129]
## Requirement - what kind of business use case are you trying to solve?

The C++ Jaeger client always populates the "ip" tag with 127.0.0.1 in my environment (Docker containers running on a local machine), which makes the tag useless.

## Problem - what in Jaeger blocks you from solving the requirement?

Incorrect implementation in https://github.com/jaegertracing/jaeger-client-cpp/blob/7e9a135b362c47f7e4d42e0693b05b91a70e6888/src/jaegertracing/net/IPAddress.cpp#L45: Looking at the implementation, this will return the address of the first encountered `AF_INET` interface, which could be the loopback interface.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I know that getting a node's IP address is an ambiguous question with no right answer -- which interface do you use? Many nodes have more than one IP address, especially in the network-virtualized environments of Kube clusters, but the loopback interface is almost definitely the *wrong* answer.

A better solution would allow overriding the IP address via environment variables and/or the tracer config, as per #105.

**Comment by isaachier** [comment]
Yes I agree that implementing environment variable overrides is necessary for this case and others. Maybe we can expand this issue to cover all of the environment variable overrides listed here: https://www.jaegertracing.io/docs/1.6/client-features.

**Comment by tudor** [comment]
Yes, I'm a bit miffed that I have to set *both* environment variables (for the Java servers) and generate a YAML config (for the C++ servers).

**Comment by tudor** [comment]
@isaachier: This also has the side effect of disabling clock skew adjustment in the collector, as the clock skew adjustment algorithm assumes that spans with the same value for the "ip" tag come from the same host, and thus do not need adjustment. https://github.com/jaegertracing/jaeger/blob/50429cb55aee9280e39621a0b5aae3c2afe5d190/model/adjuster/clockskew.go#L77

**Comment by tudor** [comment]
The Java client resolves the local hostname (as would be returned by `gethostname()`) instead of using the first `AF_INET` interface: https://github.com/jaegertracing/jaeger-client-java/blob/41a9d104a83bfcf7ed388daf4724dcd7f68237ff/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java#L107

**Comment by yzpangu** [comment]
The latest version doesn't solve this problem. How did you solve it？
Trying to build master branch code won't do either
