### ISSUE TITLE
Jaeger client deadlocks with span of duration 0

### ISSUE THREAD

**Issue by tudor** [jaegertracing/jaeger-client-cpp#131]
## Requirement - what kind of business use case are you trying to solve?

I have a deadlock in a process that uses the Jaeger C++ client. I debugged it to show a deadlock in the case where a span's duration is zero. Details in the PR.

## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger bug in `Span::FinishWithOptions`.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Sending a PR.

**Comment by isaachier** [comment]
Fixed in #132.
