### ISSUE TITLE
Automatically add tag with value of jaeger-debug-id header

### ISSUE THREAD

**Issue by burritts** [jaegertracing/jaeger-client-cpp#136]
## Add  jaeger-debug-id header value as tag in C++ client

We're using Envoy and have configured it to use native Jaeger tracing.  If we force a trace by sending a jaeger-debug-id header it is very hard/impossible to find the trace in the Jaeger UI. The C++ client does not set a a tag with the value of the jaeger-debug-id header.  The use case is that as a developer I'd like to be able to initiate an operation from the browser, and then find the corresponding trace and see what services were involved in handling the request.  

## Problem - what in Jaeger blocks you from solving the requirement?

The docs for the Go client say: 
> When Jaeger sees this header in the request that otherwise has no tracing context, it ensures that the new trace started for this request will be sampled in the "debug" mode (meaning it should survive all downsampling that might happen in the collection pipeline), and the root span will have a tag as if this statement was executed:
> span.SetTag("jaeger-debug-id", "some-correlation-id")

 AFAICT the debug header is partially supported by the C++ client.  When the debug header is present in the incoming headers, Jaeger C++ client sets the debug and sampled flags on the SpanContext so the trace does get written out, but it does not set a tag with the value of the debug header.  On an even slightly busy system it is pretty much impossible to find the trace in the Jaeger UI.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Set a tag with name "jaeger-debug-id" with value of the jaeger-debug-id header before reporting the span.

FWIW, I did attempt to fix this myself.  I can build Envoy and libjaegertracing_plugin.so and debug them, and guessed my way through the code, but I could never get the library I built to actually trace anything from Envoy.  My C++ is so rusty that I doubt if any PR from me would be accepted anyway.

In Tracer.cpp Tracer::StartSpanWithOptions I think it is necessary to pass the debug ID from the parent SpanContext here (eg: add the debugId parameter after StrMap()):
            ```ctx = SpanContext(traceID, spanID, parentID, flags, StrMap(), _debugId_);```

and set a tag, perhaps in Span::FinishWithOptions() conceptually like:
```
if ( !_context.debugID().empty() ) {
      // TODO: get the configured debug header?
      SetTag( "jaeger-debug-id", _context.debugID());
    } 
```

## Any open questions to address

Note that the name of the debug header is configurable in the C++ client.  Perhaps the name of the tag should be the same as the configured header name.

**Comment by isaachier** [comment]
Interesting. Thank you for finding this issue.

**Comment by edify42** [comment]
@isaachier Any hope of implementing this feature? We'd like to force tracing for certain requests to help debug microservices issues we might have
