### ISSUE TITLE
Does jaeger-client-cpp support constructing the tracer data in X-B3 format and reporting it?

### ISSUE THREAD

**Issue by hafent** [jaegertracing/jaeger-client-cpp#141]
Does jaeger-client-cpp support constructing the tracer data in X-B3 format and reporting it? Or can I use zipkin-cpp-opentracing to match jaeger to construct the tracer data in X-B3 format?

**Comment by isaachier** [comment]
As of now it does not. Potentially will be supported in the future.

**Comment by hafent** [comment]
Can I use this software combination ("opentracing-cpp"&& "zipkin-cpp-opentracing" && "nginx-opentracing" && "jaeger") to build and propagate X-B3 tracer data?

**Comment by yurishkuro** [comment]
Many Jaeger clients provide B3 codecs that can be enabled on the tracer.  It may not have been implemented in C++ client.
