### ISSUE TITLE
get root span

### ISSUE THREAD

**Issue by DavitSo** [jaegertracing/jaeger-client-cpp#142]

**Comment by DavitSo** [comment]
can someone answer how to get root span from tracer.
Or is any other way to do this?

**Comment by isaachier** [comment]
@DavitSo what is your goal here? Typically speaking, spans are local to the service emitting that part of the trace. I can try to help if I find out more about your use case.

**Comment by DavitSo** [comment]
@isaachier  thanks for answer. I'm new at open tracing. from your answer I understood my problem. thanks.

**Comment by isaachier** [comment]
Glad to help :)
