### ISSUE TITLE
Is there way to build jaeger-client-cpp with all library as static lib

### ISSUE THREAD

**Issue by voltento** [jaegertracing/jaeger-client-cpp#146]
Hello! I have the next problem.
I must to build the jaeger cpp client library and link it to my application. I must be one binary application. So, I have to have a static jaeger cpp library.
I link it like that `target_link_libraries(mylib jaegertracing::jaegertracing-static)`

And build the library like that
 
```
git clone https://github.com/jaegertracing/jaeger-client-cpp.git
cd jaeger-client-cpp &&
mkdir -p build && cd build &&
../../usr/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=OFF -DHUNTER_ENABLED=OFF -DCMAKE_C_FLAGS="-fpic" -DCMAKE_CXX_FLAGS="-fpic"  .. &&
make -j8 && make install || exit 5
../../usr/bin/cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DHUNTER_ENABLED=OFF -DCMAKE_C_FLAGS="-fpic" -DCMAKE_CXX_FLAGS="-fpic"  .. &&
make -j8 && make install || exit 5
```
But, in the end, the library stiil needs to have the libbost as shared library and shows error like that

> error while loading shared libraries: libboost_system.so.1.65.0: cannot open shared object file: No such file or directory

So, I wonder, Is there way to build jaeger-client-cpp with all library as static lib?
Thank you very much for your response.

**Comment by isaachier** [comment]
Try using `-DBUILD_SHARED_LIBS=off`. If that doesn't work, use that flag and also `-DHUNTER_BUILD_SHARED_LIBS=on`.
