### ISSUE TITLE
Question: is arm supported?

### ISSUE THREAD

**Issue by aledbf** [jaegertracing/jaeger-client-cpp#151]
## Requirement - what kind of business use case are you trying to solve?

ARM support 

## Problem - what in Jaeger blocks you from solving the requirement?

Unexpected error building nginx-opentracing (https://github.com/opentracing-contrib/nginx-opentracing/issues/91)

Error: kubernetes/ingress-nginx#3852 (comment)
Note: arm64 works fine

From the error, I see there is an issue building the thrift dependency but I don't know how to add a verbose/debug flag to see exactly the issue. I tried to update hunter to 0.23.143 but results in the same issue

**Comment by lucacome** [comment]
Any updates on this?
