### ISSUE TITLE
Create a span from given parent Span Id / parent Trace Id

### ISSUE THREAD

**Issue by lff0305** [jaegertracing/jaeger-client-cpp#155]
Is is possible to create a span with given parent span Id / parent tracer Id ?

In my project, a Java service will call C++ service by HTTP. From Java side, we can put the trace Id / span Id in the HTTP Request, and send to C++ service.

The question here, is that can we create a span from the span Id / Tracer Id ? Or any way to set them ?

So we can associate the Spans from Java and from C++ together under same trace.

Thanks.

**Comment by isaachier** [comment]
Yes there is. It is hard to give an example without knowing what HTTP library/API you are using for the C++ application. This [method](https://github.com/jaegertracing/jaeger-client-cpp/blob/master/src/jaegertracing/Tracer.h#L177-L198) will extract a span context from your custom opentracing::HTTPHeadersReader implementation (see https://github.com/opentracing/opentracing-cpp/blob/master/include/opentracing/propagation.h). That can be used in conjunction with Tracer::StartSpanWithOptions to begin a child span on the C++ application.

**Comment by yurishkuro** [comment]
I don't know if this question is about very basic thing or about very custom thing. Nothing in it indicates the latter.

ctx = tracer.extract(... httpheaders ...)
span = tracer.startSpan(... childOf(ctx))

This works regardless of sender or receiver language. Trace/span IDs are an implementation detail which the instrumentation doesn't need to care about.

**Comment by isaachier** [comment]
Right. Just to be clear, I do not believe any particular customization is being requested here. However, the specifics of the HTTP header reader is tightly coupled with the HTTP library use. For example, reading headers from a raw TCP stream would be a bit different than iterating through a map of parsed headers. Seeing as C++ has no standard HTTP library (each projects seems to use its own), giving an example is difficult without knowing specifics.

**Comment by lff0305** [comment]
Great. Thanks for your help. Since this question is very language / framework specific, I will follow the ideas here to do some tests. Will update the results in this thread.
