### ISSUE TITLE
Default sampling server url misses /sampling path

### ISSUE THREAD

**Issue by JorritSalverda** [jaegertracing/jaeger-client-cpp#157]
At https://github.com/jaegertracing/jaeger-client-cpp/blob/v0.4.2/src/jaegertracing/samplers/Config.h#L45 the default sampling server url for retrieving remote sampling strategies is set to `http://127.0.0.1:5778`, but this should be `http://127.0.0.1:5778/sampling` instead.

If you retrieve `http://127.0.0.1:5778/?service=my-service` the jaeger-agent returns

```json
{"strategyType":0,"probabilisticSampling":{"samplingRate":0.5}}
```

While at the correct url `http://127.0.0.1:5778/sampling?service=my-service` it returns

```json
{"strategyType":"PROBABILISTIC","probabilisticSampling":{"samplingRate":0.5}}
```

If the sampling strategies file looks like this:

```json
{
  "service_strategies": [
  ],
  "default_strategy": {
    "type": "probabilistic",
    "param": 0.5
  }
}
```

**Comment by yurishkuro** [comment]
Agreed. Can you create a PR with a fix?

**Comment by JorritSalverda** [comment]
Fixed by https://github.com/jaegertracing/jaeger-client-cpp/pull/158.

**Comment by hiruna** [comment]
@JorritSalverda it's not merge yet, please merge

**Comment by DavitSo** [comment]
HI Any update on this?

**Comment by DavitSo** [comment]
Hi , Its only client lib side fix?
