### ISSUE TITLE
try (Scope s = tracer.activateSpan(span)) {...} pattern interacts poorly with error logging

### ISSUE THREAD

**Issue by doctorpangloss** [jaegertracing/jaeger-client-cpp#161]
## Requirement - what kind of business use case are you trying to solve?

This is tracing used to diagnose issues in a complex, real-time video game server. Exception tracing is very valuable here.

## Problem

Here is actual code from a Java-based game engine server that I've begun to instrument using the most contemporary pattern.

```
Tracer tracer = GlobalTracer.get();
Span span = tracer.buildSpan("ServerGameContext/resume")
		.asChildOf(getSpanContext())
		.start();
try (Scope s = tracer.activateSpan(span)) {
	if (!isRunning()) {
		endGame();
	}
	while (!updateAndGetGameOver()) {
		span.log(ImmutableMap.of("turn", getTurn(), "activePlayerId", getActivePlayerId()));
		if (!isRunning()) {
			break;
		}
		startTurn(getActivePlayerId());
		while (takeActionInTurn()) {
			span.log(ImmutableMap.of("turn", getTurn(), "activePlayerId", getActivePlayerId(), "actionsThisTurn", getActionsThisTurn()));
			if (!isRunning()) {
				break;
			}
		}
		if (getTurn() > GameLogic.TURN_LIMIT) {
			break;
		}
	}
	endGame();
} catch (Throwable t) {
	// TODO: Log the error
	throw t;
} finally {
	span.finish();
}
```

Observe `// TODO: Log the error`. At this line of code, the scope has actually been closed, due to the semantics of **try-with-resources**, which is undesired. This is an example of an implementation that will fail, a common pattern:

```
Span span = GlobalTracer.get().scopeManager().activeSpan();
if (span == null) {
	return;
}
Tags.ERROR.set(span, true);
span.log(ImmutableMap.of(Fields.EVENT, "error", Fields.ERROR_OBJECT, throwable, Fields.MESSAGE, throwable.getMessage()));
```

Naturally, passing the `span` that was defined already won't work, because it's closed.

## Proposal

Author a pattern on your `README` for how people should actually use this, because I keep running into deprecated code!

## Workaround

Do not use **try-with-resources**.

**Comment by isaachier** [comment]
Please post this in the Java client repo: [jaeger-client-java[(https://github.com/jaegertracing/jaeger-client-java).
