### ISSUE TITLE
Linking the shared lib without hunter fails because it tries to link with the static opentracing

### ISSUE THREAD

**Issue by ecourreges-orange** [jaegertracing/jaeger-client-cpp#162]
When trying to build with a manual download of all latest deps and:

> cmake -DHUNTER_ENABLED=0 -DBUILD_TESTING=0 ..

I get this error because it tries to link with the static opentracing which does not have -fPIC:
> /usr/bin/ld: /usr/local/lib/libopentracing.a(propagation.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
> /usr/local/lib/libopentracing.a: error adding symbols: Bad value

Removing static fixes the problem:
> sed -i -e 's/opentracing-static/opentracing/g' CMakeLists.txt

What do you think is the long term solution? Ask opentracing to add -fPIC?

I did not figure out how to use the hunter install (which recompiles boost) without conflicting with the boost libraries already used in my project (the ubuntu apt versions).

Thank you.

**Comment by ideepika** [comment]
+1 small change yet would be useful to adapt a shared library, rather than using a static build

**Comment by cula** [comment]
+1 for this. 
another problem is that libjaegertracing.so demands for static lib: libyaml-cppd.so.0.6.2. which doesn't exist in most system shared lib like on linux. (The standard on is something like libyaml-cpp.xxxx. ). even the build output of yaml-cpp source code is libyaml-cpp.a

**Comment by ideepika** [comment]
> +1 for this.
> another problem is that libjaegertracing.so demands for static lib: libyaml-cppd.so.0.6.2. which doesn't exist in most system shared lib like on linux. (The standard on is something like libyaml-cpp.xxxx. ). even the build output of yaml-cpp source code is libyaml-cpp.a

Just as a workaround you can build yaml-cpp from source with flag `-DBUILD_SHARED_LIBS=ON` while compiling using CMake.

**Comment by cula** [comment]
I made it finally on ubuntu with gcc/g++ 7. I'm not sure if this can work again, but here is my resolution for reference.
`
apt-get install automake bison flex libtool libssl-dev -y && \
cd ~/temp && \
version=release-0.5.3 && git clone -b $version https://github.com/jbeder/yaml-cpp.git && \
cd yaml-cpp && \
CXX=g++-7 CC=gcc-7 cmake -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true . && make && make install && \
cd ~/temp && \
version=v3.7.2 && git clone -b $version https://github.com/nlohmann/json.git && \
cd json && \
CXX=g++-7 CC=gcc-7 cmake -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true . && make && make install && \
checkLastSuccess "install nlohmann json fails"
cd ~/temp && \
version=1.5.x && git clone -b $version https://github.com/opentracing/opentracing-cpp.git && \
cd opentracing-cpp/ && git submodule init && git submodule update && \
CXX=g++-7 CC=gcc-7 cmake -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true CMakeLists.txt && make && make install
cd ~/temp && \
version=0.11.0 && git clone -b $version https://github.com/apache/thrift.git \
&& cd thrift && CXX=g++-7 CC=gcc-7 ./bootstrap.sh && CXX=g++-7 CC=gcc-7 ./configure && make install
cd ~/temp && \
version=v0.5.0 && git clone https://github.com/jaegertracing/jaeger-client-cpp.git && \
cd jaeger-client-cpp/ && git checkout $version && git submodule init && git submodule update && \
CXX=g++-7 CC=gcc-7 cmake -DHUNTER_ENABLED=OFF -DBUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true CMakeLists.txt && make && make install
`

**Comment by suab321321** [comment]
@cula bro you helped me a lot..thank you for the information :)

**Comment by grimmmyshini** [comment]
If Hunter is used to install dependencies, the `libyaml-cppd.so.0.6` resides inside the `include` folder in `.hunter`. A symbolic link to this library can be made in `usr/local/lib` as another workaround. I am not sure if this would be the way to go but it works.

**Comment by KamalaRamas** [comment]
I'm building yaml-cpp from source with -DBUILD_SHARED_LIBS=ON. This succeeds and produces a library with the names libyaml-cpp.so, libyaml-cpp.${version}.so, but does not produce libyaml-cppd.so.${version} as required by libjaegertracing.so. What am I missing here?

Thanks.

**Comment by suab321321** [comment]
@KamalaRamas yeah this is the same issue I was facing, build its static library `-DBUILD_SHARED_LIBS=ON` and then link with 
`libyaml-cpp.a` and also add this `-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true`
and be sure use opentracing `1.5.x`

**Comment by KamalaRamas** [comment]
I did but was unable to generate libyaml-cpp.so. I also have opentracing installed from the master branch, so I'm guessing that is > 1.5. Finally, I enabled hunter and found libyaml-cppd.so generated in one of the subfolders in the .hunter folder which I then moved to /usr/local/lib/ and got the build working.
