### ISSUE TITLE
Jaeger client always populates the "ip" tag with 127.0.0.1

### ISSUE THREAD

**Issue by yzpangu** [jaegertracing/jaeger-client-cpp#163]
The C++ Jaeger client always populates the "ip" tag with 127.0.0.1

**Comment by yurishkuro** [comment]
Other Jaeger clients fix this by allowing the `ip` tracer tag to be specified externally, e.g.
https://github.com/jaegertracing/jaeger-client-go/pull/402

**Comment by yzpangu** [comment]
how about when  we can fix this problem  and release a new version v0.4.3

**Comment by yurishkuro** [comment]
feel free to propose a PR

**Comment by yzpangu** [comment]
Can you show me a docker image address ,to compile this project

**Comment by yzpangu** [comment]
when built using CMake,it is very slowly and unsuccess
--------------------------------------------------------
log out :

loading initial cache file /root/.hunter/_Base/2c5c6fc/77ad682/92161a9/cache.cmake
loading initial cache file /root/.hunter/_Base/2c5c6fc/77ad682/92161a9/Build/nlohmann_json/args.cmake
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/c++
-- Check for working CXX compiler: /usr/local/bin/c++ -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/.hunter/_Base/2c5c6fc/77ad682/92161a9/Build/nlohmann_json/Build
Scanning dependencies of target nlohmann_json-Release
[  6%] Creating directories for 'nlohmann_json-Release'
[ 12%] Performing download step (download, verify and extract) for 'nlohmann_json-Release'
-- Downloading...
   dst='/root/.hunter/_Base/Download/nlohmann_json/3.1.2/7b668b6/v3.1.2.tar.gz'
   timeout='none'
-- Using src='https://github.com/nlohmann/json/archive/v3.1.2.tar.gz'

**Comment by juanvasquezreyes** [comment]
I'm getting same result 127.0.0.1, I cannot add it as a tag cause I dont want to hardcoded it, the ip could be change, is there an automated way of getting the right ip?

these are the two ips I see in my ifconfig, not sure why I'm getting the LOOPBACK ip
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet x.x.x.x  netmask 255.255.255.0  broadcast 10.212.174.255
        
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        

I'm using the latest version libjaegertracing.so.0.4.2
