### ISSUE TITLE
Large timings when using envoy and libjaegertracing_plugin.so for tracing ( with envoy )

### ISSUE THREAD

**Issue by TheSpbra1n** [jaegertracing/jaeger-client-cpp#176]
Hi! 
Description:
Hi. We use envoy-proxy with over 10000 rps in one cluster. Typically, the query time is kept at:

full request time(serviceA -> envoy -> serviceB): 0.2-0.5 seconds
connection establishment time (envoy -> serviceB): 0.48-0.49 milliseconds

After adding libjaegertracing_plugin.so ( www.envoyproxy.io/docs/envoy/latest/start/sandboxes/jaeger_native_tracing.html ) timings increase to:

full request time(serviceA -> envoy -> serviceB): 0.5-2 seconds
connection establishment time (envoy -> serviceB): 20-150 milliseconds
( a little better with the latest libjaegertracing_plugin.so , connection establishment time at 2 and more milliseconds )

Without libjaegertracing_plugin.so, or with built in zipkin`s tracing, or with libjaegertracing_plugin.so and with less rps - timings are normal.

I created a issue for envoy (https://github.com/envoyproxy/envoy/issues/8307) but I think it's on the side libjaegertracing_plugin.so :-(

**Comment by mdouaihy** [comment]
Hi @TheSpbra1n. Do you have a profiling (callgrind) for your use case?

**Comment by TheSpbra1n** [comment]
Not relevant, thank you!
