### ISSUE TITLE
Support configuring client from environment variables

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-cpp#178]
Most Jaeger clients support that, cf. https://www.jaegertracing.io/docs/client-features/

* [x] code changes https://github.com/jaegertracing/jaeger-client-cpp/pull/181
* [ ] documentation changes (similar to https://github.com/jaegertracing/documentation/pull/306)

**Comment by yurishkuro** [comment]
Note: it is better to support `FromEnv()` function on an existing Config object, so that, for example, a default config could be programmatically populated by the application, but could be also overwritten with environment variables. Cf. https://github.com/jaegertracing/jaeger-client-go/pull/436

**Comment by mdouaihy** [comment]
Hi @yurishkuro, any comment on this PR?

**Comment by yurishkuro** [comment]
Re-opening since we also need documentation change

**Comment by yurishkuro** [comment]
@bhavin192 fyi in case you want to pick it up
