### ISSUE TITLE
Is gcc >= 4.9 requirement is really mandatory?

### ISSUE THREAD

**Issue by defanator** [jaegertracing/jaeger-client-cpp#179]
## Requirement - what kind of business use case are you trying to solve?

Build a working combo of nginx + opentracing-nginx + jaeger tracer plugin on CentOS 7.6.

## Problem - what in Jaeger blocks you from solving the requirement?

Jaeger tracer has the requirement of having gcc >= 4.9:
https://github.com/jaegertracing/jaeger-client-cpp/blob/master/CMakeLists.txt#L56-L59

CentOS 7.6 has 4.8.5.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I've removed the check for gcc >= 4.9, and jaeger tracer builds just fine. Here's the platform details:

```
# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
```

## Any open questions to address

Obviously there are (were?) the reasons of requiring newer gcc compiler, but I failed to identify those using github issues/PRs. Maybe the version check should be updated to allow using 4.8?

**Comment by yurishkuro** [comment]
@mdouaihy thoughts?

**Comment by mdouaihy** [comment]
hi @defanator, this change implies that the library supports compilers older than 4.9. 

While it seems to compile with 4.8, this will add more burdens for future evolutions of the code and/or its dependencies.

**Comment by joconnor-openet** [comment]
std::regex is irretrievably broken in gcc <4.9 which causes all the tests to fail 

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53631
