### ISSUE TITLE
Support building with libc++

### ISSUE THREAD

**Issue by lizan** [jaegertracing/jaeger-client-cpp#183]
## Requirement

We're considering switch Envoy default build to libc++, and all released Istio proxy are already built with libc++ since August.

## Proposal

Add cmake flags to not adding `-static-libstdc++`, and propagate `-stdlib=libc++` to the dependencies pulled by Hunter. I did a hack https://github.com/tetratelabs/getenvoy-package/issues/35#issuecomment-541380474 but that's not a good one.

**Comment by prahaladramji** [comment]
@lizan could you please share your snippet to help compile this plugin so it's compatible with envoy 1.13.1
I've been trying to build using `envoyproxy/envoy-build-ubuntu:latest` haven't been successful yet.

Thanks.

**Comment by maksim-paskal** [comment]
I've successfully built `jaeger-client-cpp v0.5.0` and works well with `envoyproxy/envoy:v1.15.0` - and there is no need to install some specials packages, it's statically linked to libc++ and libc++abi

*jaeger-client-cpp-build.patch* - same as [here](https://github.com/jaegertracing/jaeger-client-cpp/issues/183#issuecomment-595790140)

*Dockerfile*
```
FROM ubuntu:bionic

RUN apt update \
&& apt install -y build-essential git curl libc++-dev libc++abi-dev clang-8 \
&& curl -L -O "https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.sh" \
&& bash cmake-3.11.0-Linux-x86_64.sh --skip-license

RUN echo 'INPUT(-l:libc++.a -l:libc++abi.a -lm -lpthread)' > /usr/lib/x86_64-linux-gnu/libc++.so

WORKDIR /tmp
RUN git clone --recurse-submodules --branch=v0.5.0 https://github.com/jaegertracing/jaeger-client-cpp.git

WORKDIR /tmp/jaeger-client-cpp/
ADD ./jaeger-client-cpp-build.patch ./jaeger-client-cpp-build.patch
RUN git apply jaeger-client-cpp-build.patch
RUN ./scripts/build-plugin.sh

FROM envoyproxy/envoy:v1.15.0

COPY --from=0 /tmp/jaeger-client-cpp/build/libjaegertracing_plugin.so /usr/local/lib/libjaegertracing_plugin.so
```

or you can use precompiled binary
```
FROM envoyproxy/envoy:v1.15.0

ADD --chown=envoy:envoy https://github.com/maksim-paskal/jaeger-client-cpp/releases/download/v0.5.0/libjaegertracing_plugin.so /usr/local/lib/libjaegertracing_plugin.so
```

jaeger-client-cpp v0.6.0 is not compatible with envoy v1.15.0
```
failed to load dynamic library: opentracing: versions of opentracing libraries are incompatible
```
