### ISSUE TITLE
startTime generate by cpp client is different from jaeger UI->Trace JSON

### ISSUE THREAD

**Issue by trustyred** [jaegertracing/jaeger-client-cpp#187]
## Requirement - what kind of business use case are you trying to solve?
I print the string value of startTime through jaegertracing::Span member function startTimeSystem(). 
```c++
//span_ctx is a protobuf class
const jaegertracing::SpanContext parentCtx(jaegertracing::TraceID(span_ctx.traceidhigh(),span_ctx.traceidlow()),span_ctx.spanid(), span_ctx.parentid(), '1', jaegertracing::SpanContext::StrMap());
opentracing::StartSpanOptions options;
options.references.emplace_back(opentracing::SpanReferenceType::ChildOfRef, &parentCtx);
string span_name = "xxxx";
span = jaegertracing::Tracer::Global()->StartSpanWithOptions(span_name, options);
jspan = dynamic_cast<jaegertracing::Span*>(span.get());
const std::string str_msecs = std::to_string(std::chrono::duration_cast<std::chrono::microseconds>(t1.time_since_epoch()).count()) ;
//LOG_INFO is macro for log print
LOG_INFO("opentracing start_time: %s", str_msecs.c_str());
```

After trigger above section, I made a comparison between the startTime of the log output and the startTime of the jaeger UI->Trace JSON.

output of log:
```
opentracing start_time:1573624361028552
```

output of jaeger UI:
```json
{
 "traceID": "87ec623d599da813",
"spanID": "b8183ede326ba3ae",
"flags": 49,
"operationName": "xxxx",
"references": [
    {
        "refType": "CHILD_OF",
        "traceID": "87ec623d599da813",
        "spanID": "7f34e64e54742e4"
    }
],
"startTime": 1573624360263038,
"duration": 1463,
"tags": [
    {
        "key": "internal.span.format",
        "type": "string",
        "value": "proto"
    }
],
"logs": [],
"processID": "p3",
"warnings": null
},
```
I'd like to know the difference is caused by what?
I send the span to jaeger through udp port 6831, here is my configuration.
```yml
disabled: false
reporter:
  logSpans: true
  localAgentHostPort: xx.xx.xx.xx:6831
sampler:
  type: const
  param: 1
```

## Problem - what in Jaeger blocks you from solving the requirement?
I have export many span in order, and according to the log print startTime, it's also in order.
But, when we check the jaeger UI output, the span is out of order. For deeply investigated the cause, I found the timestamp is different from jaegertracing::Span member function startTimeSystem() and Trace JSON.

**Comment by yurishkuro** [comment]
Possible reasons:
  - time zones. Seems unlikely as “epoch” time should be zone-agnostic. 
  - JavaScript messing with long integers. Also seems unlikely, since the current microsecond timestamps are not that large to overflow JS number. 

Have you checked how the timestamps look in the storage?

**Comment by trustyred** [comment]
Thank yurishkuro for the reply!
I using the docker all-in-one, Is there any ways to check the value store at it?

**Comment by yurishkuro** [comment]
no, all-in-one keeps data in memory. You can spin up Cassandra or Elasticsearch in Docker, it's pretty easy, and there you can see the data via their own APIs (cqlsh or REST)

**Comment by trustyred** [comment]
I'll have a try, Thank you!
