### ISSUE TITLE
Hunter failed to download yaml-cpp because of SHA1 hash mismatch.

### ISSUE THREAD

**Issue by Ba777** [jaegertracing/jaeger-client-cpp#188]
**what kind of business use case are you trying to solve?**

I am trying to build Jaeger-client-cpp

**## Problem - what in Jaeger blocks you from solving the requirement?**

When I try to build, I am getting the below error:

-- downloading...
       src='https://github.com/hunter-packages/yaml-cpp/archive/v0.6.2-0f9a586-p1.zip'
       dst='/home/bala/.hunter/_Base/Download/yaml-cpp/0.6.2-0f9a586-p1/956C2B5/v0.6.2-0f9a586-p1.zip'
       timeout='none'
-- verifying file...
       file='/home/bala/.hunter/_Base/Download/yaml-cpp/0.6.2-0f9a586-p1/956C2B5/v0.6.2-0f9a586-p1.zip'
-- SHA1 hash of
    /home/bala/.hunter/_Base/Download/yaml-cpp/0.6.2-0f9a586-p1/956C2B5/v0.6.2-0f9a586-p1.zip
  does not match expected value
    expected: '956C2B5FBF5AA0EB8EF5EF890C0328B3AA357A13'
      actual: '956c2b5fbf5aa0eb8ef5ef890c0328b3aa357a13'
-- Hash mismatch, removing...
CMake Error at Build/yaml-cpp-Release-prefix/src/yaml-cpp-Release-stamp/download-yaml-cpp-Release.cmake:161 (message):
  Downloading failed

gmake[2]: *** [yaml-cpp-Release-prefix/src/yaml-cpp-Release-stamp/yaml-cpp-Release-download] Error 1
gmake[1]: *** [CMakeFiles/yaml-cpp-Release.dir/all] Error 2
gmake: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/bala/.hunter/_Base/29f1068/6d869b0/74005d6/Build/yaml-cpp
[hunter ** FATAL ERROR **] [Directory:/home/bala/.hunter/_Base/Download/Hunter/0.23.201/29f1068/Unpacked/cmake/projects/yaml-cpp]

------------------------------ ERROR -----------------------------
    https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html
------------------------------------------------------------------

CMake Error at /home/bala/.hunter/_Base/Download/Hunter/0.23.201/29f1068/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  /home/bala/.hunter/_Base/Download/Hunter/0.23.201/29f1068/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_error_page)
  /home/bala/.hunter/_Base/Download/Hunter/0.23.201/29f1068/Unpacked/cmake/modules/hunter_download.cmake:617 (hunter_fatal_error)
  /home/bala/.hunter/_Base/Download/Hunter/0.23.201/29f1068/Unpacked/cmake/projects/yaml-cpp/hunter.cmake:72 (hunter_download)
  /home/bala/.hunter/_Base/Download/Hunter/0.23.201/29f1068/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
  CMakeLists.txt:100 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/home/bala/jaeger-client-cpp/build/CMakeFiles/CMakeOutput.log".

**Comment by Ba777** [comment]
@yurishkuro - Any thoughts?

**Comment by mdouaihy** [comment]
Hello @Ba777, for some reason, the expected is capital letters and the actual is not.

expected: '956C2B5FBF5AA0EB8EF5EF890C0328B3AA357A13'
actual: '956c2b5fbf5aa0eb8ef5ef890c0328b3aa357a13'

This seems for me to be a Hunter issue. I suggest you file an issue on the Hunter project.
