### ISSUE TITLE
Any plan to release new version to upgrade to OpenTracing 1.6.0

### ISSUE THREAD

**Issue by XuPeng-SH** [jaegertracing/jaeger-client-cpp#189]
what kind of business use case are you trying to solve?
We're going to integrate Opentracing-1.6.0 in our project.

what in Jaeger blocks you from solving the requirement?
The latest released version only support opentracing1.5.0.

**Comment by mdouaihy** [comment]
HI @XuPeng-SH , the upgrade to OpenTracing 1.6.0 was done with change #209

**Comment by dblackdblack** [comment]
can we have a tagged release of jaeger-client-cpp that uses this PR?  I like to pin to specific versions of libraries
