### ISSUE TITLE
remove yaml dependency

### ISSUE THREAD

**Issue by cula** [jaegertracing/jaeger-client-cpp#193]
Is there anyway to remove yaml dependency?

in CMakeLists.txt,
`cmake_dependent_option(
  JAEGERTRACING_WITH_YAML_CPP "Use yaml-cpp to parse config files" ON
  "NOT JAEGERTRACING_BUILD_CROSSDOCK" ON)`

this means `JAEGERTRACING_WITH_YAML_CPP` is always ON in any case.

Since hunter will install yaml6+ which needs at least C++11, in my env, I cannot use C++11

**Comment by mdouaihy** [comment]
Hi @cula, the library wont compile with a pre-C++11 compiler.

Are you sure Yaml-Cpp is the only problem?

**Comment by cula** [comment]
I find something to work around it by disabling hunter. thx
CXX=g++-7 CC=gcc-7 cmake -DHUNTER_ENABLED=OFF -DBUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true CMakeLists.txt
