### ISSUE TITLE
Update to latest version of Thrift

### ISSUE THREAD

**Issue by david-antiteum** [jaegertracing/jaeger-client-cpp#195]
The Jaeger client cpp uses an old version of Thrift that lacks proper support for cmake config files. This has been addressed in the current versions but they are not compatible with jaeger as they have remove the stdcxx.h header file (see case #174 for other affected users).

Any chance to update to the latest Thrift version?

Thanks.

**Comment by yurishkuro** [comment]
cc @mdouaihy

**Comment by mdouaihy** [comment]
hello @david-antiteum,

It's always a good idea to update a dependency version. Do you have a PR to suggest?

Please note that the thrift update should not break the compatibility with the Jaeger backend.

**Comment by david-antiteum** [comment]
Hi @mdouaihy 

Unfortunately no. I have no experience with Thrift and your code must be changed a bit. My primary interest is to have jaeger in vcpck and this is the missing piece.

Thanks

**Comment by mdouaihy** [comment]
ok, no problem, I can handle that but it'll  require some time because we'll have to update the thrift version packaged in Hunter (0.12 -> 0.13).

**Comment by smartnet-club** [comment]
It's good idea do not add to repository [generated thrift files](https://github.com/jaegertracing/jaeger-client-cpp/tree/master/src/jaegertracing/thrift-gen), but add to CMakeLists.txt code to generate them.

**Comment by smartnet-club** [comment]
In version v0.13.0 of thrift, the name of generated config file ThriftConfig.cmake. (Starts with upper case)
So we have error:

CMake Error at jaeger-client-cpp/v0.5.0/lib/cmake/jaegertracing/jaegertracingConfig.cmake:35 (find_package):
  Could not find a package configuration file provided by "thrift" with any
  of the following names:

    thriftConfig.cmake
    thrift-config.cmake

**Comment by suab321321** [comment]
@mdouaihy should we just include create thriftConfig.cmake and use find_file and find_library to find thrift?

**Comment by sirzooro** [comment]
Any update on this? I am trying to build on CentOS 8 with hunter disabled, and build fails because thrift-0.13.0-2 in CentOS8 does not have thrift/stdcxx.h.

**Comment by david-antiteum** [comment]
Nothing yet. There is a pull request trying to solve this problem: # 239 from @ideepika but it has not been accepted yet. And, as @smartnet-club already points out, the root of the problem is adding thrift-generated files to the repository rather than having a CMake rule to generate them during the build process.

**Comment by robem** [comment]
The following list of open CVEs suggests that an upgrade of Thrift is most desirable https://www.opencve.io/cve?vendor=apache&product=thrift

**Comment by CC-Libby** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fmoraes74** [comment]
@yurishkuro Has this been fixed?

**Comment by yurishkuro** [comment]
Library is deprecated, please see README

**Comment by fmoraes74** [comment]
@yurishkuro Thanks. It would have been nice to state so when you closed the issue.

**Comment by yurishkuro** [comment]
Yes, sorry, I linked the corresponding README commit to closed PRs, but it was too much work to do the issues, and GH doesn't allow to add a comment in bulk when closing.
