### ISSUE TITLE
Include compiled library for 0.5.0 release

### ISSUE THREAD

**Issue by anpryl** [jaegertracing/jaeger-client-cpp#197]
Release [`0.4.2`](https://github.com/jaegertracing/jaeger-client-cpp/releases/tag/v0.4.2) has `libjaegertracing_plugin.linux_amd64.so` in assests.
Is it possible to provide the same for [`0.5.0`](https://github.com/jaegertracing/jaeger-client-cpp/releases/tag/v0.5.0) release?

**Comment by julienvey** [comment]
Could we consider included compiled binary for each release ?

Or maybe a Docker image that includes them, that we could use in a multistage docker build
