### ISSUE TITLE
/bin/sh -c ./scripts/build-plugin.sh' returned a non-zero code: 127

### ISSUE THREAD

**Issue by ghakfoort** [jaegertracing/jaeger-client-cpp#198]
hi,

I try to create a docker image but somehow I'm not able to finish the build. I get this error:

./scripts/build-plugin.sh: line 29: ./DynamicallyLoadTracerTest: No such file or directory
The command '/bin/sh -c ./scripts/build-plugin.sh' returned a non-zero code: 127

I used release jaeger-client-cpp-0.5.0

Maybe it's an issue, maybe it isn't and I did  something wrong. Can anyone help me with this? 

thanks in advance!

**Comment by mdouaihy** [comment]
Hi @ghakfoort, 

would you please post the full build logs?

**Comment by dblackdblack** [comment]
I'm having the same issue. I reworked the Doclerfile.build to be this:
```Dockerfile
FROM debian:stable AS jaeger-builder
RUN apt-get update \
    && apt-get install --yes build-essential curl git \
    && curl -L -O "https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.sh" \
    && bash cmake-3.11.0-Linux-x86_64.sh --skip-license

RUN mkdir /src \
    && cd /src \
    && git clone --recurse-submodules --branch=v0.5.0 https://github.com/jaegertracing/jaeger-client-cpp.git \
    && cd /src/jaeger-client-cpp \
    && ./scripts/build-plugin.sh
```
which is cleaner and doesn't depend on having a locally checked out copy of the repo (it uses git clone instead).

My build logs are available at https://gist.github.com/dblackdblack/940f639708892abd87da1012da01e9df
