### ISSUE TITLE
remote sampling strategy fails silently on setting the strategyType

### ISSUE THREAD

**Issue by ecourreges-orange** [jaegertracing/jaeger-client-cpp#201]
Using the latest master
My jaeger-agent answers this for my service name, which seems correctly typed:
`{"strategyType":0,"probabilisticSampling":{"samplingRate":0.1}}
`  

When configuring the sampling in type remote, pointing to my agent, the RemotelyControlledSampler downloads and parses the json fine, however there is a **silent exception in RemotelyControlledSampler.cpp**:
```
void RemotelyControlledSampler::updateSampler()
...
    } catch (const std::exception& ex) {
        std::cout << "samplerQueryFailure 1 " << ex.what() << std::endl;
        _metrics.samplerQueryFailure().inc(1);
        return;
...
```
Which gives me this on program output:

> samplerQueryFailure 1 [json.exception.type_error.302] type must be string, but is number

If I go in RemoteSamplingJSON.h:151 and change like this:
`
    // FIELD_FROM_JSON(response, strategyType);
    response.__set_strategyType(SamplingStrategyType::PROBABILISTIC);
`
The code goes through and **my remote configuration is properly loaded**.

I am not using a hunter build, but a CMake build on ubuntu 18.04 bionic beaver lts.

I don't understand how it's supposed to implicitely convert a json number (0) to the enum SamplingStrategyType::PROBABILISTIC, and apparently it thinks it wants a string according to the json exception, so **I don't understand how to properly fix this**, any ideas?

Here is my sample program for reference:
Compilation: g++ -std=c++11 -o jaegenv jaegenv.cpp -lopentracing -ljaegertracing
Code:
```
#include <jaegertracing/Tracer.h>
#include "opentracing/ext/tags.h"
#include <stdlib.h>

void initOpenTracer()
{
    auto config = jaegertracing::Config();

    setenv("JAEGER_SERVICE_NAME", "valkey-unit-test", 1);
    setenv("JAEGER_DISABLED", "false", 1);
    setenv("JAEGER_AGENT_HOST", "localhost", 1);
    setenv("JAEGER_AGENT_PORT", "6831", 1);
    setenv("JAEGER_REPORTER_LOG_SPANS", "true", 1);
    setenv("JAEGER_REPORTER_MAX_QUEUE_SIZE", "", 1);
    setenv("JAEGER_REPORTER_FLUSH_INTERVAL", "10000", 1);
    setenv("JAEGER_SAMPLER_TYPE", "remote", 1);
    setenv("JAEGER_SAMPLER_PARAM", "1", 1);
    setenv("JAEGER_SAMPLER_SERVER_URL", "http://localhost:5778", 1);

    config.fromEnv();

    std::shared_ptr<opentracing::Tracer> tracer;
    try
      {
        tracer = jaegertracing::Tracer::make(
                                             config.serviceName(),
                                             config,
                                             jaegertracing::logging::consoleLogger());
        std::cout << "Init OK\n" ;
      }
    catch (std::exception& e)
      {
        std::cout <<  "Failed initializing Jaeger Tracer, using NoopTracer because: " << e.what() << std::endl;
        tracer = opentracing::MakeNoopTracer();
      }
    opentracing::Tracer::InitGlobal(
                                    std::static_pointer_cast<opentracing::Tracer>(tracer));
}

int main(int argc, char **argv)
{
  initOpenTracer();
  auto tracer = opentracing::Tracer::Global();

sleep(3);
  for ( int i = 0 ; i < 100; i++) {
    std::string spanName = "test" + std::to_string(i);
    auto span = tracer->StartSpan(spanName);

    std::string query;
    span->SetTag(opentracing::ext::http_url, query);
    jaegertracing::Span* jSpan = dynamic_cast<jaegertracing::Span*>(span.get());
    std::cout << i << " isSampled() ? " << jSpan->context().isSampled() << std::endl;
    span->Finish();
  }
}
```

**Comment by yurishkuro** [comment]
You need to use /sampling endpoint on the agent, not the root /.

**Comment by ecourreges-orange** [comment]
Thanks a lot, I should have tried it first, I saw that both were answered by the agent but indeed didn't notice the difference

/sampling
> {"strategyType":"PROBABILISTIC","probabilisticSampling":{"samplingRate":0.1}}

/whatever
> {"strategyType":0,"probabilisticSampling":{"samplingRate":0.1}}

**Comment by yurishkuro** [comment]
Did you see some documentation that suggested to use the root / endpoint?

It is only supported as a legacy format for some old clients.

**Comment by ecourreges-orange** [comment]
> 
> 
> Did you see some documentation that suggested to use the root / endpoint?

Indeed, on the main README.md there is an example with http://jaeger-agent.local:5778 which I corrected in my PR: https://github.com/jaegertracing/jaeger-client-cpp/pull/200

I now have proper remote sampling working with an environment variables config.
Thanks
