### ISSUE TITLE
"No buffer space available, code=105" occurred at span send

### ISSUE THREAD

**Issue by trustyred** [jaegertracing/jaeger-client-cpp#207]
## Requirement - what kind of business use case are you trying to solve?

I make performance test for my c++ component.
During test some code logic will execute frequently, it also cause many span was created.
The error occurred when jaeger cpp lib prepare to send span to collector.

https://github.com/jaegertracing/jaeger-client-cpp/blob/master/src/jaegertracing/ThriftSender.cpp#L120

I just add localAgentHostPort to tracing config yaml, so my effect transport is udp.

I think the error root cause is that our span bytes over the system tx buf.
https://github.com/jaegertracing/jaeger-client-cpp/blob/master/src/jaegertracing/utils/UDPTransporter.h#L65

## Problem - what in Jaeger blocks you from solving the requirement?
In my opinions, add item of reporter to control the value of _maxSpanBytes(https://github.com/jaegertracing/jaeger-client-cpp/blob/master/src/jaegertracing/ThriftSender.cpp#L86) can be work. 

If my consideration is wrong, could you pls give me some other suggestions? thank you.

**Comment by yurishkuro** [comment]
You can construct your own UDPSender with custom max packet size. But it's better to fix your kernel limit to allow 64Kib UDP packets. See https://www.jaegertracing.io/docs/1.16/client-libraries/#emsgsize-and-udp-buffer-limits

**Comment by trustyred** [comment]
Thank for your suggestion! I construct my own UDPSender to reduce max packet size.
