### ISSUE TITLE
Send span issue

### ISSUE THREAD

**Issue by DavitSo** [jaegertracing/jaeger-client-cpp#220]

**Comment by DavitSo** [comment]
Hi All 
I get crash in my code
Could you please take a look?
Sorry for wrong place if it is.
Thanks

**Comment by DavitSo** [comment]
Somehow agent got dead. Could it affect to crash program?

**Comment by ecourreges-orange** [comment]
> 
> 
> Somehow agent got dead. Could it affect to crash program?

I think you need to make sure that the string that you use for setTag is not deleted before you call Finish() on the span, I had issues with strings or char * that were out of scope when calling Finish().

**Comment by DavitSo** [comment]
Thanks for response
Actually my environment run for a long time and it happens first time, and not continuously.
That's why the crash reason is not  clear for me.

**Comment by DavitSo** [comment]
Hi All, 
Could someone give advice how to avoid this crash?
Thanks.
