### ISSUE TITLE
Enable Jaeger Arm64 images on official Docker repo

### ISSUE THREAD

**Issue by Jingzhao123** [jaegertracing/jaeger-client-cpp#228]
## Enable Jaeger Arm64 images on official Docker repo
Hi all,
The Jaeger is wildly used in Cloud Native software (e.g. Istio ). But i found that the arm64 images are still not exist in official dockerhub. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?
In previous commits, Jaeger has been enabled on Arm64. And, as far as i know, the Travis also has already support arm64 architecture. I think it is a good time to enable Jaeger Arm64 images in official docker repository. So, could we enable Jaeger arm images on official docker repository ?

**Comment by yurishkuro** [comment]
If you're asking for Docker images for Jaeger backend components, then this is a wrong repository and there is already a ticket in the main one: https://github.com/jaegertracing/jaeger/issues/2292

Please reopen if it's something else.

**Comment by Jingzhao123** [comment]
Thanks.
