### ISSUE TITLE
Socket errors on Windows not reported with WSAGetLastError()

### ISSUE THREAD

**Issue by shooshx** [jaegertracing/jaeger-client-cpp#230]
I'm getting this funny error message:

Could not send span Failed to write message, numWritten=-1, size=3667: The operation completed successfully., code=0

The code here:
https://github.com/jaegertracing/jaeger-client-cpp/blob/4ee8a66868fad5c70aaf50c46a8cdad9d71adb3f/src/jaegertracing/utils/HTTPTransporter.h#L63

only takes errno and does not look at WSAGetLastError() that would return the error code on windows.

**Comment by mdouaihy** [comment]
Hi @shooshx,

do you have a use case to reproduce the error?

**Comment by shooshx** [comment]
No, but I've definitely seen it happen in production. Maybe it was some intermittent issue where the server was offline for a few seconds. Having a useful error code on that message would have been nice for debugging it.

**Comment by shooshx** [comment]
So I added the WSAGetLastError call to the log and the code is 10054 "Connection reset by peer."
Does the client not retry the socket connection when this happens?
