### ISSUE TITLE
How to know if a `Tracer` has been connected to the jaeger backend

### ISSUE THREAD

**Issue by suab321321** [jaegertracing/jaeger-client-cpp#233]
Is there any way to know if my `Tracer` has been successfully connected to jaeger backend.

when cant connect to backend `ERROR: cannot connect to socket: Cannot connect socket to remote address { scheme="http", host="127.0.0.1", port=5778, path="", query="" }`
but I need to check for this programatically which I cant do with this console output

OS : ubuntu 18.04
jaeger - v0.5.0

**Comment by suab321321** [comment]
Okay I did not find any method to do so, so one use internal libraries of Jaeger which uses to connect to host
```
#include <jaegertracing/net/IPAddress.h>
#include <jaegertracing/net/Socket.h>
void check(){
try{
jaegertracing::net::Socket socket;
        socket.open(AF_INET, SOCK_STREAM);
        const std::string serverURL = configuration.sampler().kDefaultSamplingServerURL; 
        socket.connect(serverURL);
}catch(...){}
}
```
if it throws error then it is unable to reach host, this method is costly I agree but this is the only viable solution I find

**Comment by suab321321** [comment]
@mdouaihy is there any other viable solution to this? if not I will try to open PR for this

**Comment by mdouaihy** [comment]
Hi @suab321321, Do you want to know if the Jaeger tracer was connected or just if there is the remote collector is reachable?

**Comment by suab321321** [comment]
Whether Jaeger Tracer is connected or not?

**Comment by mdouaihy** [comment]
Hi @suab321321, what I am having problem to understand is what would you do if the tracer wont be able to connect? Also, what would you do in case the spans are sent via UDP to the agent and not directly to the collector?

**Comment by suab321321** [comment]
@mdouaihy  I have a method which uses `std::call_once` to initialize a tracer to its backend, if connected successfully, then `once_flag` will be set and initialization wont be called again, but if not connected then `once_flag` will not be set and this method will be called again to initialize a tracer. So I need a way to know whether jaeger has been connected to backend or not.

**Comment by yurishkuro** [comment]
@suab321321 I don't think it's a good approach to keep re-trying to initialize the tracer. Normally the connectivity issue should be handled internally by the senders. Are you really trying to prevent your application from starting if tracing telemetry cannot be exported?

**Comment by suab321321** [comment]
my application will continue to run even if tracer is not connected, but if my tracer is connected once I will save the time of reconnecting my tracer again

**Comment by yurishkuro** [comment]
If your application is already running, why do you care if tracer is connected or not?

**Comment by mdouaihy** [comment]
@suab321321, I understand the need. however, I think that this should be handled by the jaeger senders as those should also handle the connection loss, reconnection, etc.

**Comment by suab321321** [comment]
my application is c++ server, fetching every request, if my tracer is connected then a macro is set `WITH_JAGER` if this is set then spans commands are used if not set spans command are not used.  It is a kind of optimization

**Comment by suab321321** [comment]
@mdouaihy shouldnt there a way to check, like a bool varible passed to connector function, I will be happy to open a PR for this :)

**Comment by suab321321** [comment]
Oh okay, I see UDP protocal is the main issue here, I got it,
Yeah I m trying both find a way to avoid connection if jaeger is connected or if jaeger is not connected then not to invoke the spans.
I got it thanks @yurishkuro @mdouaihy.
