### ISSUE TITLE
No compatible with fbthrift

### ISSUE THREAD

**Issue by linuxpham** [jaegertracing/jaeger-client-cpp#243]
## Requirement - what kind of business use case are you trying to solve?
fbthrift library

## Problem - what in Jaeger blocks you from solving the requirement?
Error when compiling with fbthrift

## Proposal - what do you suggest to solve the problem or improve the existing situation?
How I can compile it with fbthrift library ?

**Comment by mdouaihy** [comment]
Hi @linuxpham , what is the problem you are facing?
