### ISSUE TITLE
Jaeger cpp client on alpine seems to crash when used with opentracing

### ISSUE THREAD

**Issue by shreyasdn** [jaegertracing/jaeger-client-cpp#245]
## Requirement - what kind of business use case are you trying to solve?
I am trying to use the jaeger tracing tool with nginx and opentracing. I am able to compile from sources using alpine musl library, gcc and libstdc++ in a docker file using the instructions in the readme.

## Problem - what in Jaeger blocks you from solving the requirement?
When i use the compiled library from the docker the container crashes with the code 139. Commenting out the section using the library seems to start the container correctly.

**Comment by mdouaihy** [comment]
hi @shreyasdn, do you have any additional details on your issue?

**Comment by mpiexec** [comment]
It works, but only with nginx:1.16.1-alpine image
How to build with 1.18.0-alpine?
