### ISSUE TITLE
Initialization of Tracer

### ISSUE THREAD

**Issue by suab321321** [jaegertracing/jaeger-client-cpp#246]
I want to undertand how initialization works for `opentracing::v2::Tracer` internally, I have two programs

```
main(){
t.initTracer();// tracer init code just once
while(a--){
Span s = rootSpan("root");
}
```
this code is not  producing spans

2nd code
```
main(){
while(a--){
t.initTracer();// tracer init code for each itr
Span s = rootSpan("root");
}
```
this code is producing spans.

How come first code is not producing spans and second does?
I m trying to trace ceph object storage cluster. The clusetr recevies thousands of request always incoming so if I need to initialize each time for new request isnt this will make my code considerablly slower?

@mdouaihy @yurishkuro  @isaachier

**Comment by mdouaihy** [comment]
Hi @suab321321 , do you have more details about this problem?

**Comment by suab321321** [comment]
@mdouaihy hey my problem got resolved my bad that I forgot to close it.
I just have one question when we `opentracing::initTracer(static_cast<tracer>(tracer)` then this means that I m initializing the internal opentracing tracer and using it to store spans, but what if I reinitialize it with same tracer then the spans stored inside the prev tracer will get replaced, then how are the spans still maintained, just a brief overview will work
Thanks
