### ISSUE TITLE
Jeager client initialization is too slow. 

### ISSUE THREAD

**Issue by andreyryabov** [jaegertracing/jaeger-client-cpp#247]
## Problem - what in Jaeger blocks you from solving the requirement?

I'm trying to sample client connection time with jaeger. it works well but! the initialization takes way too long. 5000ms and more. This makes it impractical on the client site. 

Here is the code I use. 
```
    jg::samplers::Config spCfg("const", 1);
    jg::reporters::Config rpCfg(100, chrono::seconds(3), false, "127.0.0.1:6831");
    jg::propagation::HeadersConfig prCfg;
    jg::baggage::RestrictionsConfig bgCfg;
    vector<jg::Tag> jTags;
    jg::Config config(false, spCfg, rpCfg, prCfg, bgCfg, serviceName, jTags);
    auto tracer = jaegertracing::Tracer::make(serviceName, config, jg::logging::nullLogger());
    _tracer = ot::Tracer::InitGlobal(std::static_pointer_cast<ot::Tracer>(tracer));
```

**Comment by yurishkuro** [comment]
> sample client connection time

Please elaborate, I don't understand what you mean and what tracer initialization has to do with it.

**Comment by andreyryabov** [comment]
```
    auto tracer = jaegertracing::Tracer::make(serviceName, config, jg::logging::nullLogger());
```
This line of code take 5 seconds to execute, regardless of the configuration. This is blocks us from using it on the client side. Users won't wait 5 seconds for the app to start.

**Comment by mdouaihy** [comment]
HI @andremarianiello,

would you please indicate what is taking time? do you have a profile of the execution?

I run the code you provided and it's taking les than 2s.

**Comment by andremarianiello** [comment]
@mdouaihy I think you meant to tag @andreyryabov

**Comment by mdouaihy** [comment]
yes indeed; sorry for that
