### ISSUE TITLE
Message too long, code=40

### ISSUE THREAD

**Issue by andreyryabov** [jaegertracing/jaeger-client-cpp#249]
Getting following messages printed to log. After which no spans are being recorded. 

```
Could not send span Failed to write message, numWritten=-1, size=17728: Message too long, code=40
Could not send span Failed to write message, numWritten=-1, size=17728: Message too long, code=40
Could not send span Failed to write message, numWritten=-1, size=17728: Message too long, code=40

```

**Comment by yurishkuro** [comment]
Are you using UDP? Do your OS settings allow 64k UDP messages?  See https://www.jaegertracing.io/docs/1.20/client-libraries/#emsgsize-and-udp-buffer-limits

**Comment by andreyryabov** [comment]
Yes it was UDP MTU issue.
I would suggest print more informative error message or checking precondition ahead of time.  

Your comment resolves the issue. 
Thank you.

**Comment by yurishkuro** [comment]
Feel free to propose a PR with more detailed error message. Often the MTU issues manifest with different errors, I am not sure if there is a robust way of detecting it.
