### ISSUE TITLE
Unit test: Socket.testFailBind fails when run as "root"

### ISSUE THREAD

**Issue by harinreddy** [jaegertracing/jaeger-client-cpp#266]
** Description of the bug **
The following unit test fails when run as a privileged user ( “root”)
Socket.testFailBind

** How to reproduce **
As a “root” perform one of the following:

```
mkdir build
cd build
cmake ../
make  -j 16

make test
```

The following message show the failure:

```
[ RUN      ] Socket.testFailBind
…./jaegertracing/jaeger-client-cpp/src/jaegertracing/net/SocketTest.cpp:84: Failure
Expected: socket.bind(IPAddress::v4("127.0.0.1", 1)) throws an exception of type std::system_error.
  Actual: it throws nothing.
[  FAILED  ] Socket.testFailBind (0 ms)

make UnitTest
./UnitTest
The following message shows the failure:
[ RUN      ] Socket.testFailBind
…./jaegertracing/jaeger-client-cpp/src/jaegertracing/net/SocketTest.cpp:84: Failure
Expected: socket.bind(IPAddress::v4("127.0.0.1", 1)) throws an exception of type std::system_error.
  Actual: it throws nothing.
[  FAILED  ] Socket.testFailBind (0 ms)
```

When run as a non-privileged user the test passes successfully.

**Expected behavior**
All the other unit tests pass whether run as a privileged user or non-privileged user.
In order to have a uniform behavior across all the test suite, the Socket.testFailBind is expected to produce the same result whether run as a privileged or non-privileged user.
  

**Version:**
 - OS: [Any OS other than WIN32]
 - Jaeger version: [current development branch]
 - Deployment: [baremetal or any virtual machine: vm, docker]

**What troubleshooting steps did you try?**
The following ASSERT_THROW statement 

```
#ifndef WIN32
TEST(Socket, testFailBind)
{
    Socket socket;
    socket.open(AF_INET, SOCK_STREAM);
    ASSERT_THROW(socket.bind(IPAddress::v4("127.0.0.1", 1)) , std::system_error);
}
#endifin 
```

listed in .//jaeger-client-cpp/src/jaegertracing/net/SocketTest.cpp
failed when run as privileged user because the port number (“1”) used in the “socket.bind” call is a reserved port and the “socket.bind” passes successfully, thus failing ASSERT_THROW macro call.

One way to fix this is to change the port number from “1” to some invalid port number such as “-1”. This will cause “socket.bind” call to fail whether run as a privileged or non-privileged user thus allowing the ASSERT_THROW macro to complete successfully.

**Comment by harinreddy** [comment]
Hi,
Thanks for your feedback. Changing the port to “-1” did not work. It looks like the port may be defaulting to “0” when an invalid port is specified. However, when the ip is changed to some uncommon ip such as “1.0.0.1” the Socket.bind call fails throwing an exception. If this change looks OK we shall submit a PR request.

Regarding the motivation for using “root” while running the unit tests, there is no motivation. We just stumbled on it. This is our first encounter with jaegertracing tool trying to port to IBM ppc64le platform and it so happened that the login id was “root” and we did a quick build and test and encountered the issue. We thought it would be good to have that fixed so that it would not cause any one to chase a non-issue. We understand now that the typical usage scenario does not use privileged user ids.

Thanks

**Comment by yurishkuro** [comment]
I am getting successful pings from 1.0.0.1 so I don't think it's a good alternative. I suggest just closing this, since running test as root sounds like a bad idea in principle (tests could do other "bad" things like trying to create dirs/files).

**Comment by Abhijit-Mane** [comment]
Hi @yurishkuro 

Thanks for your inputs. A technically valid IP like **1.0.0.1** was used earlier. The code below fails (using a technically invalid 
IP (**>255**).

3scale/jaeger-client-cpp/src/jaegertracing/net/SocketTest.cpp:40: Failure
Expected: socket.bind(IPAddress::v4("**1.2.3.256**", 1)) throws an exception of type std::system_error.
Actual: it throws a different type.
[  FAILED  ] Socket.testFailBind (0 ms)

So, I think we have 3 options: -
1.) Use invalid IP (as above) which should work as expected regardless of user
2.) Add note in README.md requiring to run tests as non-root
3.) Close issue (no changes)

Please let me know which you recommend.

**Comment by yurishkuro** [comment]
option 1 is fine

**Comment by harinreddy** [comment]
It turned out that invalid IP address  such as“1.0.0.256” did not work. Since the error thrown is not what ASSERT_THROW was expecting.

Expected: socket.bind(IPAddress::v4("1.0.0.256",1)) throws an exception of type std::system_error.
  Actual: it throws a different type.
Resulting in the failure of 
ASSERT_THROW(socket.bind(IPAddress::v4("1.0.0.256",1)) , std::system_error);

Considering significant code examination and changes needed to make this work and potential propagation of errors to other parts of the code, we suggest keeping the code as is (and may be a warning line in README not to use root to build and test ). 

Closing the issue.
