### ISSUE TITLE
Add support for adding tracer tags via config yaml

### ISSUE THREAD

**Issue by Frefreak** [jaegertracing/jaeger-client-cpp#274]
## Requirement - what kind of business use case are you trying to solve?

Currently config's tags (and tracer's tags) support setting by `JAEGER_TAGS` env with `fromEnv` method. However in some use cases there's no easy way to pass environment variable to it, only code/config yaml can be altered. 

## Problem - what in Jaeger blocks you from solving the requirement?

In our scenario we need to add a specific tag (process tag) to the span, but also can not set environment variable as we like. So we wish to have a way to set the tags in another way. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

We propose to add tags parsing logic from config yaml. That is, a config like this:

```yaml
disabled: false
reporter:
  logSpans: true
tags:
  tag1: 1337
  tag2: some value
sampler:
  type: const
  param: 1
```
will render the resulting span looks like this(converted by opentelemetry's jaeger receiver, so that's why we need it in process tags):

![image](https://user-images.githubusercontent.com/7122156/124885906-570fa200-e006-11eb-8630-70069edb6618.png)

This only requires adding something like below in `Config.h`:
```cpp
    static std::vector<Tag> parseTags(const YAML::Node node) {
        if (!node.IsDefined() || !node.IsMap()) {
          return std::vector<Tag>();
        }
        std::vector<Tag> tags;
        for (auto it=node.begin(); it != node.end(); it++) {
          std::string key = it->first.as<std::string>();
          std::string value = it->second.as<std::string>();
          tags.emplace_back(key, value);
        }
        return tags;
    }
```

Better yet, also providing some method like `AddTag` or `SetTag` for config/tracer to directly modify the tags.

## Any open questions to address

Supporting various value types other than string seems not easy (I'm not very experienced in cpp and the yaml-cpp lib :cry:). But just like `JAEGER_TAGS` which set all value as string, we consider this is ok. 

If this is reasonable to add we can prepare a PR. WDYT?

**Comment by yurishkuro** [comment]
+1
