### ISSUE TITLE
My jaeger version is 1.23, and the jaeger-collector component has enabled --sampling.strategies-reload-interval, but the collected logs show that the sampling strategy is still old

### ISSUE THREAD

**Issue by huangjiecheng** [jaegertracing/jaeger-client-cpp#276]
**Describe the bug**
When I used the remote sampling strategy, I modified the sampling strategy configuration file of jaeger-collector, and the call chain collected by jaeger-client-cpp still used the original sampling strategy without refreshing.

**To Reproduce**
1. Deploy jaeger-agent on the same machine as jaeger-client-cpp and use the default remote sampling strategy.
2.Deploy the jaeger-collector on the other host and specify the sampling strategy configuration file.Flags: --sampling.strategies-file  --sampling.strategies-reload-interval
3.Modify the sampling strategy configured for the jaeger-collector.
4.The sampling strategy used in the sampling result is still the original configuration file.

**Expected behavior**
The used sampling strategy must be the same as the latest configured sampling strategy .

**Screenshots**
![image](https://user-images.githubusercontent.com/44957335/125716313-2d130fab-afee-4b83-a57e-e19adce3789a.png)

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.23.0
 - Deployment:bare metal
 - Nginx version: openresty/1.17.8.2

**What troubleshooting steps did you try?**
-Tracer config file: {"service_name":"***","disabled":false,"sampler":{"samplingRefreshInterval":1,"param":"1","type":"remote"},"reporter":{"localAgentHostPort": "127.0.0.1:6831","logSpans":true},"propagation_format":"w3c"}
-Jaeger-agent: ./jaeger_agent --reporter.grpc.host-port=jaeger-collector.host:14250

**Additional context**

**Comment by huangjiecheng** [comment]
How does jaeger-agent receive sampling policy updates from jaeger-collector?

**Comment by sharninder** [comment]
@huangjiecheng Did you find a workaround for this bug ? I'm using the jaeger support built into nginx and that uses this library and I'm seeing the same issue.

**Comment by huangjiecheng** [comment]
> round for this bug ? I'm using the jaeger support built into nginx and that uses this library and I'm seeing the same i
The document mentioned that the jaeger built into nginx does not support dynamic refresh of remote sampling

**Comment by sharninder** [comment]
@huangjiecheng I think your complete comment didn't come through.
