### ISSUE TITLE
[Bug]: W3C Propagation is wrongfully encoding debug span flag into traceparent

### ISSUE THREAD

**Issue by andremarianiello** [jaegertracing/jaeger-client-cpp#293]
### What happened?

Go OpenTelemetry libraries cannot extract W3C propagated span context injected by jaeger-client-cpp. This results in a new trace being started instead of continuing an existing trace.

### Steps to reproduce

1. Use jaeger-client-cpp in w3c propagation mode to inject a span context into HTTP headers
2. Try to extract that span context using a w3c compliant library (I used the Golang otel libraries)

### Expected behavior

According to https://www.w3.org/TR/trace-context/#other-flags

> The behavior of other flags, such as (00000100) is not defined and is reserved for future use. Vendors MUST set those to zero.

jaeger-client-cpp is setting a flag it should not be. I would expect the trace flags to be 00 for a non-sampled span and 01 for a sampled span, regardless of whether the span is a debug span or not.

### Additional context

Here is the relevant snippet that chokes on the jaeger-client-cpp generated traceparent

https://github.com/open-telemetry/opentelemetry-go/blob/v1.9.0/propagation/trace_context.go#L135-L138

**Comment by yurishkuro** [comment]
This library is deprecated.
