### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by isaachier** [jaegertracing/jaeger-client-cpp#33]
Self-explanatory issue

**Comment by ringerc** [comment]
Would be good to have a quickstart example mentioning:

* A minimal explanation of how Jaeger relates to opentracing - you configure and init opentracing with a Jaeger backend then largely use the opentracing APIs thereafter, though possibly via the Jaeger wrappers and headers (?).
* How to init a Jaeger tracing singleton and set it up via the opentracing api with `opentracing::Tracer::InitGlobal`
* the YAML config support, with a link to the configuration docs;
* This example Ryan wrote https://github.com/jaegertracing/cpp-client/issues/14
* A reference to https://github.com/opentracing-contrib/nginx-opentracing/blob/master/jaeger/src/ngx_http_jaeger_module.cpp for a more real world example

**Comment by ringerc** [comment]
@isaachier Wrote a draft for you. Code examples need checking, and I'm sure you can correct the bits I got wrong, but it should help. See above-linked commit.

**Comment by manannayak** [comment]
Thanks a lot of writing it up, Craig!

Btw - is there a plan to merge this into master?

**Comment by isaachier** [comment]
Unfortunately this isn't a pull request, it's an issue. Also, it is probably outdated at this point.

**Comment by yurishkuro** [comment]
Looks like the content is in a branch, that can be converted to a PR. Don't know about it being up to date.

**Comment by isaachier** [comment]
I think this was part of a much bigger P.R. I ultimately closed due to merge conflicts and no response from @ringerc (who is too busy to fix it at the moment). See #46.
