### ISSUE TITLE
jaeger cpp-client isn't in Hunter

### ISSUE THREAD

**Issue by ringerc** [jaegertracing/jaeger-client-cpp#51]
Jaeger `cpp-client` appears to be intended to be used exclusively from/with Hunter, but it isn't in the Hunter repository/package list (https://docs.hunter.sh/en/latest/packages.html).

Mind posting an example of how you use it in your own codebase? Do you use Hunter to find dependencies then manually link to `jaeger-cpp` its self?

(I was adding a `README` explaining how to use `jaeger-cpp` *with* Hunter and couldn't figure out how!)

**Comment by ringerc** [comment]
Presumably something like

```
# Do Hunter magic here, then
find_package(jaegertracing CONFIG REQUIRED)
```

It looks like the generated CMake config module that gets installed contains the required dependency `find_package` calls etc.

**Comment by isaachier** [comment]
Lol I have thought about adding it but haven't yet. Thanks for posting.

**Comment by ringerc** [comment]
Obvs don't mind myself ;) it just struck me as amusing but also doc'ing for
others who come along to use this.​

**Comment by isaachier** [comment]
Fixed in https://github.com/ruslo/hunter/pull/1453. Will be available in Hunter release shortly.
