### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by wolfelven** [jaegertracing/jaeger-client-cpp#70]
cpp client version is 0.2.0, when i execute “make” command after executing "cmake .", has some errors:
/Users/xujie/Desktop/C_Project/cpp-client-0.2.0/src/jaegertracing/TracerTest.cpp:139:27: error: 
      default initialization of an object of const type 'const
      jaegertracing::(anonymous namespace)::FakeSpanContext' without a
      user-provided default constructor
    const FakeSpanContext fakeCtx;
                          ^
                                 {}
1 error generated.
make[2]: *** [CMakeFiles/UnitTest.dir/src/jaegertracing/TracerTest.cpp.o] Error 1
make[1]: *** [CMakeFiles/UnitTest.dir/all] Error 2
make: *** [all] Error 2

**Comment by isaachier** [comment]
What compiler are you using?

**Comment by isaachier** [comment]
Closing for now.
