### ISSUE TITLE
Unhandled exception - Abort raised when write to the jaeger-agent fails

### ISSUE THREAD

**Issue by ankit-varma10** [jaegertracing/jaeger-client-cpp#72]
An unhandled exception when flushing spans to the local agent is causing the process to abort.

In my local testing setup, I'm using the all-in-one instance to collect the spans emitted by the application. One of my test cases involves simulating a scenario where the local Jaeger agent is unavailable. Unavailability of the Jaeger agent should not have any detrimental impact on the application (except for spans being dropped) but I'm running into an unhandled exception which is causing the application to abort.

0  0x00007f200d1041f7 in raise () from /lib64/libc.so.6
1  0x00007f200d1058e8 in abort () from /lib64/libc.so.6
2  0x00007f200d708ac5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
3  0x00007f200d706a36 in ?? () from /lib64/libstdc++.so.6
4  0x00007f200d706a63 in std::terminate() () from /lib64/libstdc++.so.6
5  0x000000000082d005 in jaegertracing::reporters::RemoteReporter::flush (this=0x108b6a60)
6  0x000000000082cccd in jaegertracing::reporters::RemoteReporter::sweepQueue (this=0x108b6a60)

Upon further investigation, I belive the reason for this is the way the client handles send failures.

UDPClient::emitBatch(...) raises an std::system_error in case the write to the socket fails. This propagates through till it reaches RemoteReporter::flush() which is currently only expecting Transport::Exception.

I have currently patched this by modifying the UDPTransport::flush() to handle std::system_error and std::logic_error.

`
int UDPTransport::flush()
{
    if (_spanBuffer.empty()) {
        return 0;
    }

    thrift::Batch batch;
    batch.__set_process(_process);
    batch.__set_spans(_spanBuffer);
    _client->emitBatch(batch);

    try {
      _client->emitBatch(batch);
    } catch (const std::system_error& ex) {
      std::ostringstream oss;
      oss << "Could not send span " << ex.what() << ", code=" << ex.code().value();
      throw Transport::Exception(oss.str(), _spanBuffer.size());
    } catch (const std::logic_error &ex) {
      std::ostringstream oss;
      oss << "Could not send span " << ex.what();
      throw Transport::Exception(oss.str(), _spanBuffer.size());
    }
    catch (...) {
      throw Transport::Exception("Could not send spans", _spanBuffer.size());
    }

    resetBuffers();

    return batch.spans.size();
}
`

**Comment by isaachier** [comment]
Great. Would you like to submit a pull request?

**Comment by ankit-varma10** [comment]
Absolutely. I'll have it up in the next couple of days.

**Comment by ankit-varma10** [comment]
Created a PR [https://github.com/jaegertracing/jaeger-client-cpp/pull/80](url)

**Comment by isaachier** [comment]
Fixed with #80.
