### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by wolfelven** [jaegertracing/jaeger-client-cpp#73]
Hello:
     my code :
     #include <iostream>
#include <jaegertracing/tracer.h>
#include <opentracing/tracer.h>
#include <stdio.h>
#include <chrono>

using namespace std;

int main(){
	cout << "Hello world !!!!" << endl;

	auto config = jaegertracing::Config(
	      false,
	      jaegertracing::samplers::Config(jaegertracing::kSamplerTypeConst, 1),
	      jaegertracing::reporters::Config(
	          jaegertracing::reporters::Config::kDefaultQueueSize,
	          std::chrono::seconds(1), true));
	std::shared_ptr<opentracing::Tracer> tracer = jaegertracing::Tracer::make("c++", config);
	  auto span = tracer->StartSpan("abc");
	  std::this_thread::sleep_for(std::chrono::milliseconds{10});
	  span->Finish();
	  std::this_thread::sleep_for(std::chrono::seconds{5});
	  tracer->Close();
	return 0;
}
And build error:
make all 
Building file: ../src/HelloWorld.cpp
Invoking: GCC C++ Compiler
clang++ -D__GXX_EXPERIMENTAL_CXX0X__ -D__cplusplus=201103L -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -stdlib=libc++ -MMD -MP -MF"src/HelloWorld.d" -MT"src/HelloWorld.o" -o "src/HelloWorld.o" "../src/HelloWorld.cpp"
Finished building: ../src/HelloWorld.cpp
 
Building target: ProjectTest
Invoking: MacOS X C++ Linker
clang++ -stdlib=libc++ -Xlinker /usr/local/lib/libopentracing.a -o "ProjectTest"  ./src/HelloWorld.o   
Undefined symbols for architecture x86_64:
  "jaegertracing::SpanContext::fromStream(std::__1::basic_istream<char, std::__1::char_traits<char> >&)", referenced from:
      operator>>(std::__1::basic_istream<char, std::__1::char_traits<char> >&, jaegertracing::SpanContext&) in HelloWorld.o
  "jaegertracing::UDPTransport::UDPTransport(jaegertracing::net::IPAddress const&, int)", referenced from:
      jaegertracing::reporters::Config::makeReporter(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, jaegertracing::logging::Logger&, jaegertracing::metrics::Metrics&) const in HelloWorld.o
  "jaegertracing::net::URI::queryEscape(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      jaegertracing::propagation::HTTPHeaderPropagator::encodeValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in HelloWorld.o
  "jaegertracing::net::URI::queryUnescape(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      jaegertracing::propagation::Propagator<opentracing::v1::TextMapReader const&, opentracing::v1::TextMapWriter const&>::parseCommaSeparatedMap(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in HelloWorld.o
      jaegertracing::propagation::HTTPHeaderPropagator::decodeValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in HelloWorld.o
      jaegertracing::propagation::Propagator<opentracing::v1::HTTPHeadersReader const&, opentracing::v1::HTTPHeadersWriter const&>::parseCommaSeparatedMap(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in HelloWorld.o
  "jaegertracing::net::IPAddress::versionFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)", referenced from:
      jaegertracing::net::IPAddress::v4(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in HelloWorld.o
  "jaegertracing::net::IPAddress::localIP(int)", referenced from:
      jaegertracing::Tracer::Tracer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<jaegertracing::samplers::Sampler> const&, std::__1::shared_ptr<jaegertracing::reporters::Reporter> const&, std::__1::shared_ptr<jaegertracing::logging::Logger> const&, std::__1::shared_ptr<jaegertracing::metrics::Metrics> const&, int) in HelloWorld.o
  "jaegertracing::logging::nullLogger()", referenced from:
      jaegertracing::Tracer::make(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, jaegertracing::Config const&) in HelloWorld.o
  "jaegertracing::metrics::StatsFactory::createGauge(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      jaegertracing::metrics::Metrics::Metrics(jaegertracing::metrics::StatsFactory&) in HelloWorld.o
  "jaegertracing::metrics::StatsFactory::createCounter(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      jaegertracing::metrics::Metrics::Metrics(jaegertracing::metrics::StatsFactory&) in HelloWorld.o
  "jaegertracing::metrics::Metrics::makeNullMetrics()", referenced from:
      jaegertracing::propagation::Propagator<opentracing::v1::TextMapReader const&, opentracing::v1::TextMapWriter const&>::Propagator() in HelloWorld.o
      jaegertracing::propagation::Propagator<opentracing::v1::HTTPHeadersReader const&, opentracing::v1::HTTPHeadersWriter const&>::Propagator() in HelloWorld.o
  "jaegertracing::metrics::Metrics::~Metrics()", referenced from:
      std::__1::__shared_ptr_emplace<jaegertracing::metrics::Metrics, std::__1::allocator<jaegertracing::metrics::Metrics> >::__on_zero_shared() in HelloWorld.o
      std::__1::__libcpp_compressed_pair_imp<std::__1::allocator<jaegertracing::metrics::Metrics>, jaegertracing::metrics::Metrics, 1u>::~__libcpp_compressed_pair_imp() in HelloWorld.o
      jaegertracing::propagation::Propagator<opentracing::v1::TextMapReader const&, opentracing::v1::TextMapWriter const&>::Propagator() in HelloWorld.o
      std::__1::__shared_ptr_pointer<jaegertracing::metrics::Metrics*, std::__1::default_delete<jaegertracing::metrics::Metrics>, std::__1::allocator<jaegertracing::metrics::Metrics> >::__on_zero_shared() in HelloWorld.o
      jaegertracing::propagation::Propagator<opentracing::v1::HTTPHeadersReader const&, opentracing::v1::HTTPHeadersWriter const&>::Propagator() in HelloWorld.o
  "jaegertracing::samplers::RemotelyControlledSampler::RemotelyControlledSampler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<jaegertracing::samplers::Sampler> const&, int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&, jaegertracing::logging::Logger&, jaegertracing::metrics::Metrics&)", referenced from:
      jaegertracing::samplers::Config::makeSampler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, jaegertracing::logging::Logger&, jaegertracing::metrics::Metrics&) const in HelloWorld.o
  "jaegertracing::reporters::RemoteReporter::RemoteReporter(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&, int, std::__1::unique_ptr<jaegertracing::Transport, std::__1::default_delete<jaegertracing::Transport> >&&, jaegertracing::logging::Logger&, jaegertracing::metrics::Metrics&)", referenced from:
      jaegertracing::reporters::Config::makeReporter(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, jaegertracing::logging::Logger&, jaegertracing::metrics::Metrics&) const in HelloWorld.o
  "vtable for jaegertracing::Tracer", referenced from:
      jaegertracing::Tracer::Tracer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<jaegertracing::samplers::Sampler> const&, std::__1::shared_ptr<jaegertracing::reporters::Reporter> const&, std::__1::shared_ptr<jaegertracing::logging::Logger> const&, std::__1::shared_ptr<jaegertracing::metrics::Metrics> const&, int) in HelloWorld.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for jaegertracing::reporters::LoggingReporter", referenced from:
      jaegertracing::reporters::LoggingReporter::LoggingReporter(jaegertracing::logging::Logger&) in HelloWorld.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ProjectTest] Error 1

16:28:45 Build Finished (took 2s.513ms)

**Comment by isaachier** [comment]
It seems you are not linking to the Jaeger C++ client library.

**Comment by isaachier** [comment]
Also, can you consolidate your issues/withdraw other duplicate issues regarding build issues.

**Comment by isaachier** [comment]
Closing for now.
