### ISSUE TITLE
Rename project to jaeger-client-cpp

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger-client-cpp#74]
To fall inline with the rest of the projects

**Comment by isaachier** [comment]
FWIW those are the only project dependencies I remember off hand.

**Comment by yurishkuro** [comment]
ok renamed

**Comment by yurishkuro** [comment]
travis https://travis-ci.org/jaegertracing/jaeger-client-cpp

**Comment by yurishkuro** [comment]
codecov https://codecov.io/gh/jaegertracing/jaeger-client-cpp

@isaachier please update readme badges

**Comment by isaachier** [comment]
Sure thing.

**Comment by yurishkuro** [comment]
thanks
