### ISSUE TITLE
MacOs gcc/clang error

### ISSUE THREAD

**Issue by wolfelven** [jaegertracing/jaeger-client-cpp#89]
Hello, everyone.When i use Eclipse to build c++ code ,that is ok.But in terminal there is link error.

clang++ -std=c++11 AMQPClientSend.cpp -o send -lSimpleAmqpClient -lopentracing -lcurl -ljaegertracing -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name AMQPClientSend.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 274.1 -v -dwarf-column-info -debugger-tuning=lldb -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0 -stdlib=libc++ -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /Users/xujie/Desktop/C_Project/AMQP_Opentrainc/src -ferror-limit 19 -fmessage-length 117 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/8h/yw85sq4j5mjf9q19rm24vv340000gn/T/AMQPClientSend-b52538.o -x c++ AMQPClientSend.cpp
clang -cc1 version 8.0.0 (clang-800.0.42.1) default target x86_64-apple-darwin15.6.0
ignoring nonexistent directory "/usr/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.11.0 -o send /var/folders/8h/yw85sq4j5mjf9q19rm24vv340000gn/T/AMQPClientSend-b52538.o -lSimpleAmqpClient -lopentracing -lcurl -ljaegertracing -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "TraceSingleton::getInstance()", referenced from:
      CreateTrace(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in AMQPClientSend-b52538.o
  "TraceSingleton::CreateTracer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, opentracing::v1::Value, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, opentracing::v1::Value> > >, std::initializer_list<std::__1::pair<opentracing::v1::string_view, opentracing::v1::Value> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, DHTracer*)", referenced from:
      CreateTrace(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in AMQPClientSend-b52538.o
  "TraceSingleton::SendContextWithRequest()", referenced from:
      CreateTrace(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in AMQPClientSend-b52538.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by isaachier** [comment]
This is a linking error in wherever `TraceSingleton::getInstance()` is defined. Try to see how Eclipse builds it and copy that command.
